apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nais.io/restricted: "true"
  name: familie-ba-infotrygd-feed
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8092
  liveness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/prod/creds/familie-ba-infotrygd-feed
        mountPath: /var/run/secrets/nais.io/azuread
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m
  ingresses:
    - https://familie-ba-infotrygd-feed.nais.adeo.no
    - https://familie-ba-infotrygd-feed.prod-fss-pub.nais.io
  azure:
    application:
      enabled: true
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-sak
          cluster: prod-gcp
        - application: familie-ba-migrering
          cluster: prod-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
