no.nav.security.jwt:
  issuer.sts:
    discoveryurl: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    accepted_audience: ${INFOTRYGD_CLIENT_ID}
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

ACCEPTED_CLIENTS: ${BA_SAK_CLIENT_ID}

spring:
  datasource:
    url: jdbc:postgresql://A01DBVL014.adeo.no:5432/familie-ba-infotrygd-feed
