STS_ISSUER:  https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration

spring:
  datasource:
    url: jdbc:postgresql://b27dbvl035.preprod.local:5432/familie-ba-infotrygd-feed-15
