no.nav.security.jwt:
  issuer.sts:
    discoveryurl: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    accepted_audience: ${INFOTRYGD_CLIENT_ID}

spring:
  datasource:
    url: jdbc:postgresql://b27dbvl015.preprod.local:5432/familie-ba-infotrygd-feed
