no.nav.security.jwt:
  issuer.sts:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${BA_SAK_CLIENT_ID}
    cookie_name: azure_token

BA_SAK_CLIENT_ID: "dummy-klient-id"