no.nav.security.jwt:
  issuer.sts:
    discoveryurl: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    accepted_audience: ${GYLDIG_SERVICE_BRUKER}
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

spring:
  datasource:
    url: jdbc:postgresql://b27dbvl015.preprod.local:5432/familie-ba-infotrygd-feed
