name: Merge queue
on:
  merge_group:
env:
  IMAGE: ghcr.io/navikt/familie-ba-infotrygd-feed:${{ github.sha }}
jobs:
  build:
    name: Bygg app for merge queue
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Bygg med maven
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml